### PR TITLE
fix sign in without a challenge

### LINKED ISSUE #247: Sign in page not loading correctly
The login logic is currently tied to hydra. If you try to go to `/ui/reset_password` without a session, you'll get redirected to sign in but the page will be shown as loading:
image

This is due to missing `login_challenge` parameter value. Similar bug can be observed when going directly to http://localhost:4455/ui/login.

### PR DESCRIPTION
**Pull request by edlerd**
# Done
- fix sign in without a challenge
- i.e. on hitting the reset_password or other settings URLs directly

fixes #247

### CODE REVIEW

File: pkg/kratos/service.go [hunk 1]
```diff
@@ -123,14 +123,19 @@ func (s *Service) CreateBrowserLoginFlow(
...
-		Cookie(httpHelpers.CookiesToString(cookies)).
-		Execute()
+		Cookie(httpHelpers.
+		CookiesToString(cookies))
+
+	if loginChallenge != "" {
+		request.LoginChallenge(loginChallenge)
+	}
+
+	flow, resp, err := request.Execute()
```
Comment (nsklikas) [inline pkg/kratos/service.go:138]: We don't have a home page, this means that the user should not log in without a login challenge OR a return to. Let's add this logic to the code, I can make this change if you want

Comment (edlerd) [reply pkg/kratos/service.go:138]: Right, we should ensure either of the two are set. I was removing the need to pass the login challenge with this change. Because users might land on the "reset password" page, and should be able to login, which was previously failing. I think the reset password page would then be the return to address, so it should be fine as you suggested.

Please, can you add commits to my branch to enforce the requirement to have either the challenge or the return to present @nsklikas ?

File: ui/pages/setup_backup_codes.tsx [hunk 2]
```diff
@@ -53,7 +53,7 @@ const SetupBackupCodes: NextPage = () => {
       .catch(async (err: AxiosError<string>) => {
         if (err.response?.data.trim() === "Failed to create settings flow") {
           setFlow(undefined);
-          window.location.href = "./login";
+          window.location.href = `./login?return_to=${window.location.pathname}`;
```
[the remark this answers is not in the document]
Comment (edlerd) [reply ui/pages/setup_backup_codes.tsx:56]: I think in those cases here we want to actually redirect, so setting the location href would be preferred.

File: ui/pages/setup_passkey.tsx [hunk 3]
```diff
@@ -53,7 +53,7 @@ const SetupPasskey: NextPage = () => {
       .catch(async (err: AxiosError<string>) => {
         if (err.response?.data.trim() === "Failed to create settings flow") {
           setFlow(undefined);
-          await router.push("./login");
+          await router.push(`./login?return_to=${window.location.pathname}`);
```
[the remark this answers is not in the document]
Comment (edlerd) [reply ui/pages/setup_passkey.tsx:56]: right, will adjust this.

**Review by nsklikas — DISMISSED** [review]

File: pkg/kratos/service.go [hunk 4]
```diff
@@ -123,14 +125,21 @@ func (s *Service) CreateBrowserLoginFlow(
...
-		LoginChallenge(loginChallenge).
 		Refresh(refresh).
-		Cookie(httpHelpers.CookiesToString(cookies)).
-		Execute()
+		Cookie(httpHelpers.
+			CookiesToString(cookies))
+
+	if loginChallenge != "" {
+		request = request.LoginChallenge(loginChallenge)
+	} else if returnTo == "" {
```
Comment (shipperizer) [inline pkg/kratos/service.go:138]: is this `loginChallenge is "abc" and returnTo is not set`?

File: pkg/kratos/service.go [hunk 5]
```diff
@@ -123,14 +125,21 @@ func (s *Service) CreateBrowserLoginFlow(
...
+		return nil, nil, ErrNoReturnToOrLoginChallenge
```
Comment (shipperizer) [inline pkg/kratos/service.go:139]:
```suggestion
		return nil, nil, fmt.Errorf("No return_to or login_challenge was provided")
```

i'd probably drop the const and tweak the tests

File: pkg/kratos/service_test.go [hunk 6]
```diff
@@ -282,6 +282,109 @@ func TestCreateBrowserLoginFlowSuccess(t *testing.T) {
...
+
+	if f != nil {
+		t.Fatalf("expected flow to be %v not  %v", nil, f)
+	}
+	if c != nil {
+		t.Fatalf("expected cookies to be %v not  %v", nil, c)
+	}
+	if err != ErrNoReturnToOrLoginChallenge {
+		t.Fatalf("expected error to be %s, not %s", ErrNoReturnToOrLoginChallenge, err)
+	}
```
Comment (shipperizer) [inline pkg/kratos/service_test.go:385]: based on https://github.com/canonical/identity-platform-login-ui/pull/294/files#diff-5e4ba31969008b305d67765d5d4c9bd50d9bcc49571f1594e97d2b152ddf1378R139

```suggestion
	if err == nil {
		t.Fatalf("expected error to be not nil")
	}
```

File: pkg/kratos/service.go (hunk 5 above)
Comment (nsklikas) [reply pkg/kratos/service.go:139]: why drop the const? I find it clearer to use only vars for generating tests, this allows you to gather them to a single place and imo makes it more manageable.

No problem to change it, just curious

File: pkg/kratos/service.go (hunk 4 above)
Comment (nsklikas) [reply pkg/kratos/service.go:138]: No, it's when `loginChallenge == "" && returnTo == ""`

Comment (shipperizer) [reply pkg/kratos/service.go:138]: as discussed probably worth being more explicit with another separate `if`

File: pkg/kratos/service.go (hunk 5 above)
Comment (shipperizer) [reply pkg/kratos/service.go:139]: main reason is we don't currently instantiate error messages this way in the codebase, i m happy to change it everywhere but i would keep it as a separate effort

 in terms of testing, fair point, at the same time, unless we are interested in the error message itself, what we should be checking is that the function errors (or at least that's my opinion)

**Review by shipperizer — APPROVED** [review]

**Review by nsklikas — APPROVED** [review]

**Comment by edlerd** [comment]
@shipperizer or @nsklikas can you merge it?
